version: 2

models:
  - name: circuits_refined
    description: "Refined circuits data, typically cleaned, transformed, and potentially enriched from the staging layer."
    columns:
      - name: circuit_id
        description: "The unique identifier for each circuit in the refined dataset."
        tests:
          - unique
          - not_null

  - name: drivers_refined
    description: "Refined drivers data, with potential cleaning, type conversions, and enrichments."
    columns:
      - name: driver_id
        description: "The unique identifier for each driver in the refined dataset."
        tests:
          - unique
          - not_null

  - name: lap_times_refined
    description: "Refined lap times data, possibly aggregated, joined with driver/race details, or with calculated metrics."
    columns:
      - name: refined_lap_time_pk
        description: "The primary key for the refined lap times. This might be a new surrogate key or a combination of existing keys."
        tests:
          - unique
          - not_null

  - name: races_refined
    description: "Refined races data, potentially joined with circuit details, weather information, or session times."
    columns:
      - name: race_id
        description: "The unique identifier for each race in the refined dataset."
        tests:
          - unique
          - not_null
      - name: race_full_date
        description: "Full date of the race, potentially combining year, round, and date fields."

  - name: results_refined
    description: "Refined race results, adding status column"
    columns:
      - name: refined_result_pk
        description: "The primary key for the refined results. This might be a new surrogate key or a combination of existing keys."
        tests:
          - unique
          - not_null
      - name: status
        description: "Full mapping on statuses from finished, disqualified, accident, etc."

  - name: weather_refined
    description: "Weather data for all the races 2020-2024"
    columns:
      - name: raceid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: tyres_refined
    description: "Tyres data for all the races and drivers 2020-2024"
    columns:
      - name: raceid
        description: "Part of the composite primary key for this table"
        tests:
          - not_null
      - name: driverid
        description: "Part of the composite primary key for this table"
        tests:
          - not_null
    #tests:
      #- dbt_utils.unique_combination_of_columns:
          #combination_of_columns:
            #- raceid
            #- driverid
            # this test will be tried in a next version.
      